// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTj80DBiV3BTUau4gweYpKmMdrfUV5BzU',
    appId: '1:70137680788:web:3171c8f0a6ee195d72f581',
    messagingSenderId: '70137680788',
    projectId: 'tari2i-c27e0',
    authDomain: 'tari2i-c27e0.firebaseapp.com',
    storageBucket: 'tari2i-c27e0.firebasestorage.app',
    measurementId: 'G-XMKR39Z2B8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY3BFfLOdKBuS2CUwsTkMtBOqGXhhkeO8',
    appId: '1:70137680788:android:97b3b3815043f64e72f581',
    messagingSenderId: '70137680788',
    projectId: 'tari2i-c27e0',
    storageBucket: 'tari2i-c27e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtdq7veZbpBstoxVnKAtT4YYUbODcA95Q',
    appId: '1:70137680788:ios:1f460ca38437fc6472f581',
    messagingSenderId: '70137680788',
    projectId: 'tari2i-c27e0',
    storageBucket: 'tari2i-c27e0.firebasestorage.app',
    iosBundleId: 'com.mycompany.john',
  );
}
